#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Sensor, S2,     rightSensor,    sensorEV3_Color, modeEV3Color_Reflected_Raw)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float CmtoDegrees(int speed, float diameterofWheel, float distance)
{
	float motorDist = 360*distance/(diameterofWheel*PI);
	/* divides the desired distance by the	cirumference of the wheels to find how many rotations it takes to get to
	achieve the distance Then wait until the motor	encoders reach this distance.It travels this distance at the desired speed then cuts off power.*/
	return motorDist;
}

task main()
{
	writeDebugStream("%d", CmtoDegrees(30, 5, 20));
}
