#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S4,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          forklift,      tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          sidelift,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void linearSlide (float xFinish, float zFinish)
{
	bool Exit1 = false;
	bool Exit2 = false;
	float xTeeth = 12;
	float zTeeth = 8;
	float zSpeed;
	float xSpeed;
	float xDistance = (xFinish - getMotorEncoder(sidelift));
	float zDistance = ((xTeeth/zTeeth)*(zFinish - getMotorEncoder(forklift)));

	if (abs(zDistance) > abs(xDistance))
	{
		xSpeed = 20;
		zSpeed = zDistance/xDistance*xSpeed;
	}
	else
	{
		zSpeed = 20;
		xSpeed = xDistance*zSpeed/zDistance;
	}
	setMotorSpeed(sidelift,xSpeed);
	setMotorSpeed(forklift,zSpeed);
	while(!(Exit1 && Exit2))
	{
		if (abs(getMotorEncoder(sidelift)) >= abs(xDistance))
		{
			setMotorSpeed(sidelift,0);
			Exit1 = true;
		}
		if (abs(getMotorEncoder(forklift)) >= abs(zDistance))
		{
			setMotorSpeed(forklift,0);
			Exit2 = true;
		}
	}
}

task main()
{
	resetMotorEncoder(sidelift);
	resetMotorEncoder(forklift);
	linearSlide(-300, -300);
	displayCenteredBigTextLine(3,"X=%f",getMotorEncoder(sidelift));
	displayCenteredBigTextLine(7,"Z=%f",getMotorEncoder(forklift));
	sleep(10000);
}
