#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S4,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          forklift,      tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          sidelift,      tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void linearSlide (float xFinish, float zFinish)
{
	bool Exit1 = false; // exit flags for
	bool Exit2 = false; // the movement loops
	float xTeeth = 12; // amount of teeth
	float zTeeth = 8;  // on each slider
	float zSpeed; // speeds of
	float xSpeed; // both sliders
	float xDistance = (xFinish - getMotorEncoder(sidelift));  		   // how far each
	float zDistance = ((xTeeth/zTeeth)*(zFinish - getMotorEncoder(forklift))); // slider needs to go

	if (abs(zDistance) > abs(xDistance)) // if the z slider has to move farther than the x slider
	{
		xSpeed = 20; // set the x slider speed to 20
		zSpeed = zDistance/xDistance*xSpeed; // set the z slider speed to the distance it has to go times xSpeed/xDistance
	}
	else // if the x slider has to move farther than the z slider
	{
		zSpeed = 20; // set the z slider speed to 20
		xSpeed = xDistance*zSpeed/zDistance; // set the x slider speed to the distance it has to go times zSpeed/zDistance
	}
	
	setMotorSpeed(sidelift,xSpeed); // set the x slider speed
	setMotorSpeed(forklift,zSpeed); // set the z slider speed
	
	while(!(Exit1 && Exit2)) // run until both exit flags are raised
	{
		if (abs(getMotorEncoder(sidelift)) >= abs(xDistance)) // if the x slider has passed the endpoint
		{
			setMotorSpeed(sidelift,0); // stop the x slider
			Exit1 = true; // raise an exit flag
		}
		if (abs(getMotorEncoder(forklift)) >= abs(zDistance)) // if the z slider has passed the endpoint
		{
			setMotorSpeed(forklift,0); // stop the z slider
			Exit2 = true; // raise an exit flag
		}
	}
}

task main()
{
	resetMotorEncoder(sidelift); // reset encoders
	resetMotorEncoder(forklift);
	
	linearSlide(-300, -300); // linear slide
	
	displayCenteredBigTextLine(3,"X=%f",getMotorEncoder(sidelift));
	displayCenteredBigTextLine(7,"Z=%f",getMotorEncoder(forklift));
	
	sleep(10000);
}
