#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S4,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          sidelift,      tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          forklift,      tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(sidelift, 40);
	setMotorSpeed(forklift, 40);

	bool exit1 = false;
	bool exit2 = false;
	while(!exit1 || !exit2)
	{
		int fpos = getMotorEncoder(forklift);
		int spos = getMotorEncoder(sidelift);
		sleep(250);

		if(fpos - getMotorEncoder(forklift) < 1)
		{
			exit1 = true;
			setMotorSpeed(forklift, 0);
		}
		if(spos - getMotorEncoder(sidelift) < 1)
		{
			exit2 = true;
			setMotorSpeed(sidelift, 0);
		}
	}

	resetMotorEncoder(forklift);
	resetMotorEncoder(sidelift);

	exit1 = false;
	exit2 = false;

	setMotorSpeed(sidelift, -40);
	setMotorSpeed(forklift, -40);

	while(!exit1 || !exit2)
	{
		int fpos = getMotorEncoder(forklift);
		int spos = getMotorEncoder(sidelift);
		sleep(250);

		if(getMotorEncoder(forklift) - fpos < 1)
		{
			exit1 = true;
			setMotorSpeed(forklift, 0);
		}
		if(getMotorEncoder(sidelift) - spos < 1)
		{
			exit2 = true;
			setMotorSpeed(sidelift, 0);
		}
	}

	int fmid = getMotorEncoder(forklift) / 2;
	int smid = getMotorEncoder(sidelift) / 2;

	exit1 = false;
	exit2 = false;

	setMotorSpeed(sidelift, 40);
	setMotorSpeed(forklift, 40);

	while(!exit1 || ! exit2)
	{
		if(getMotorEncoder(forklift) < fmid)
		{
			exit1 = true;
			setMotorSpeed(forklift, 0);
		}
		if(getMotorEncoder(sidelift) < smid)
		{
			exit2 = true;
			setMotorSpeed(sidelift, 0);
		}
	}
}
