#pragma config(Sensor, S1,     leftSensor,     sensorEV3_Color)
#pragma config(Sensor, S4,     rightSensor,    sensorEV3_Color)
#pragma config(Motor,  motorA,          sidelift,      tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          forklift,      tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(sidelift, 40); // enable both lifts at 40 speed
	setMotorSpeed(forklift, 40);

	bool exit1 = false; // exit flags
	bool exit2 = false; // exit loops when both are raised
	
	// reset both lifts up and right
	while(!exit1 || !exit2) // wait for both exit flags to be raised
	{
		int fpos = getMotorEncoder(forklift); // positions of both lifts
		int spos = getMotorEncoder(sidelift);
		
		sleep(250); // wait for 250 ms (this may be able to be lowered)

		// this checks if the forklift has reset
		if(fpos - getMotorEncoder(forklift) < 1) // if the forklift is stalling
		{
			exit1 = true; // raise the exit flag
			setMotorSpeed(forklift, 0); // stop the motor
		}
		
		// this checks if the sidelift has reset
		if(spos - getMotorEncoder(sidelift) < 1) // if the sidelift is stalling
		{
			exit2 = true; // raise the exit flag
			setMotorSpeed(sidelift, 0); // stop the motor
		}
	}

	resetMotorEncoder(forklift); // reset the motor encoders
	resetMotorEncoder(sidelift);

	exit1 = false; // reset exit flags
	exit2 = false;

	setMotorSpeed(sidelift, -40); // enable both lifts at -40 speed
	setMotorSpeed(forklift, -40);

	// reset both lifts down and left
	while(!exit1 || !exit2)
	{
		int fpos = getMotorEncoder(forklift); // get the positions of both lifts
		int spos = getMotorEncoder(sidelift);
		
		sleep(250); // wait

		// this checks if the forklift has reset
		if(getMotorEncoder(forklift) - fpos < 1) // 
		{
			exit1 = true;
			setMotorSpeed(forklift, 0);
		}
		
		
		if(getMotorEncoder(sidelift) - spos < 1)
		{
			exit2 = true;
			setMotorSpeed(sidelift, 0);
		}
	}

	int fmid = getMotorEncoder(forklift) / 2;
	int smid = getMotorEncoder(sidelift) / 2;

	exit1 = false;
	exit2 = false;

	setMotorSpeed(sidelift, 40);
	setMotorSpeed(forklift, 40);

	while(!exit1 || ! exit2)
	{
		if(getMotorEncoder(forklift) < fmid)
		{
			exit1 = true;
			setMotorSpeed(forklift, 0);
		}
		if(getMotorEncoder(sidelift) < smid)
		{
			exit2 = true;
			setMotorSpeed(sidelift, 0);
		}
	}
}
